name: Regression Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2

    # Check out a *known good* version
    # For now I am assuming 'main' is known good
    - uses: actions/checkout@v2
      repository: googlefonts/glyphsLib
      ref: main

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate test files
      run: python3 tests/gf_regression.py --generate
      env:
        PYTHONPATH: Lib

    # Now check out the version we want to test
    - uses: actions/checkout@v2

    - name: Run tests
      run: python3 tests/gf_regression.py --test
      env:
        PYTHONPATH: Lib
